print("hi")
print("decryptor by 200Amper")
pl=input("decrypt? Y/n ")
while pl=="Y":
        print("input algorithm (random letters) ")
        a=str(input("1 — "))
        b=str(input("2 — "))
        c=str(input("3 — "))
        d=str(input("4 — "))
        e=str(input("5 — "))
        f=str(input("6 — "))
        g=str(input("7 — "))
        h=str(input("8 — "))
        i=str(input("9 — "))
        j=str(input("10 — "))
        k=str(input("11 — "))
        l=str(input("12 — "))
        m=str(input("13 — "))
        n=str(input("14 — "))
        o=str(input("15 — "))
        p=str(input("16 — "))
        q=str(input("17 — "))
        r=str(input("18 — "))
        s=str(input("19 — "))
        t=str(input("20 — "))
        u=str(input("21 — "))
        v=str(input("22 — "))
        w=str(input("23 — "))
        x=str(input("24 — "))
        y=str(input("25 — "))
        z=str(input("26 — "))
        if a=="a" or b=="b" or c=="c" or d=="d" or e=="e" or f=="f" or g=="g" or h=="h" or i=="i" or j=="j" or k=="k" or l=="l" or m=="m" or n=="n" or o=="o" or p=="p" or q=="q" or r=="r" or s=="s" or t=="t" or u=="u" or v=="v" or w=="w" or x=="x" or y=="y" or z=="z":
                print("letters cannot correspond to their numeric value so it can be encrypted but with failures")
                pl=input("continue? Y/n ")
        else:
                print("give da digits")
                text=str(input())
                dz=text.replace(z,"z")
                dy=dz.replace(y,"y")
                dx=dy.replace(x,"x")
                dw=dx.replace(w,"w")
                dv=dw.replace(v,"v")
                du=dv.replace(u,"u")
                dt=du.replace(t,"t")
                ds=dt.replace(s,"s")
                dr=ds.replace(r,"r")
                dq=dr.replace(q,"q")
                dp=dq.replace(p,"p")
                do=dp.replace(o,"o")
                dn=do.replace(n,"n")
                dm=dn.replace(m,"m")
                dl=dm.replace(l,"l")
                dk=dl.replace(k,"k")
                dj=dk.replace(j,"j")
                di=dj.replace(i,"i")
                dh=di.replace(h,"h")
                dg=dh.replace(g,"g")
                df=dg.replace(f,"f")
                de=df.replace(e,"e")
                dd=de.replace(d,"d")
                dc=dd.replace(c,"c")
                db=dc.replace(b,"b")
                da=db.replace(a,"a")
                print("^")
                print(da)
                pl=input("continue? Y/n")
