print("encryptor by romka v1.4")
pl=input("encrypt? Y/n ")
while pl=="Y":
        print("input algorithm (random symbols) ")
        a=str(input("1 — "))
        b=str(input("2 — "))
        c=str(input("3 — "))
        d=str(input("4 — "))
        e=str(input("5 — "))
        f=str(input("6 — "))
        g=str(input("7 — "))
        h=str(input("8 — "))
        i=str(input("9 — "))
        j=str(input("10 — "))
        k=str(input("11 — "))
        l=str(input("12 — "))
        m=str(input("13 — "))
        n=str(input("14 — "))
        o=str(input("15 — "))
        p=str(input("16 — "))
        q=str(input("17 — "))
        r=str(input("18 — "))
        s=str(input("19 — "))
        t=str(input("20 — "))
        u=str(input("21 — "))
        v=str(input("22 — "))
        w=str(input("23 — "))
        x=str(input("24 — "))
        y=str(input("25 — "))
        z=str(input("26 — "))
        print("save it in a safe place")
        print("[",a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,"]")
        if a=="a" or b=="b" or c=="c" or d=="d" or e=="e" or f=="f" or g=="g" or h=="h" or i=="i" or j=="j" or k=="k" or l=="l" or m=="m" or n=="n" or o=="o" or p=="p" or q=="q" or r=="r" or s=="s" or t=="t" or u=="u" or v=="v" or w=="w" or x=="x" or y=="y" or z=="z":
                print("letters cannot correspond to their numeric value so it can be encrypted but with failures")
                pl=input("continue? Y/n ")
        else:
                print("now the text to be encrypted")
                tx=str(input())
                ba=tx.replace("a",a)
                bb=ba.replace("b",b)
                bc=bb.replace("c",c)
                bd=bc.replace("d",d)
                be=bd.replace("e",e)
                bf=be.replace("f",f)
                bg=bf.replace("g",g)
                bh=bf.replace("h",h)
                bi=bh.replace("i",i)
                bj=bi.replace("j",j)
                bk=bj.replace("k",k)
                bl=bk.replace("l",l)
                bm=bl.replace("m",m)
                bn=bm.replace("n",n)
                bo=bn.replace("o",o)
                bp=bo.replace("p",p)
                bq=bp.replace("q",q)
                br=bq.replace("r",r)
                bs=br.replace("s",s)
                bu=bs.replace("u",u)
                bv=bu.replace("v",v)
                bw=bv.replace("w",w)
                bx=bw.replace("x",x)
                by=bx.replace("y",y)
                bz=by.replace("z",z)
                print(bz)
                pl=input("continue? Y/n ")